name: 'unit'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.18'
          - '1.19'
    steps:
      - uses: 'actions/checkout@v3'
      - name: Set up Go
        uses: 'actions/setup-go@v3'
        with:
          go-version: '${{ matrix.go }}'
      - name: Version
        run: go version
      - name: Test
        run: go test -v